export default function() {
    return (
        <div className="flex flex-col w-full items-center">
            <h1 className="mt-8 mb-4 text-5xl text-center">Sobre nós</h1>
            <p className="w-1/2 mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac risus a enim cursus aliquam ac ut nisl. Donec dignissim faucibus aliquet. Donec ut bibendum risus. Morbi vestibulum libero vitae dolor sodales, quis tincidunt mauris blandit. Duis tincidunt massa sed consequat viverra. Nam consectetur libero mauris, nec aliquam urna commodo lacinia. Nulla eu tempus nisl. Cras efficitur erat ac pretium feugiat..</p>
            <p className="w-1/2 mb-4">Maecenas interdum hendrerit porttitor. Proin odio magna, facilisis non elementum eu, interdum et nunc. Nulla ligula tellus, feugiat vitae enim eget, venenatis elementum massa. Nulla auctor sapien erat, ut lacinia leo pulvinar et. Maecenas in dictum risus. Donec luctus ornare mauris, ut venenatis est ultrices id. In magna dui, venenatis a orci et, aliquam venenatis leo. Ut nec quam tempor, cursus nulla faucibus, laoreet orci. Duis volutpat odio non nibh volutpat, in tristique nunc ullamcorper. Etiam placerat neque mi, quis pharetra sapien fermentum ut. In pharetra tellus id dui elementum, id tincidunt nulla tempor. Nulla vel massa sem.</p>
            <p className="w-1/2 mb-4">Donec luctus ipsum in turpis feugiat pulvinar. Nam dictum velit congue risus tempor, ut dignissim lectus malesuada. Nam interdum congue odio, id consectetur velit consectetur volutpat. Cras arcu dolor, pulvinar eu dui eget, aliquam malesuada arcu. Morbi iaculis ultrices nunc, ut volutpat nisl finibus et. Ut fringilla maximus nunc sit amet rutrum. Nam eget nibh et nisl varius porta venenatis ut eros. Nullam maximus pharetra rutrum. Aenean facilisis, eros a tempus tristique, urna dui feugiat lectus, ultrices posuere ex magna sed ligula. Sed lobortis neque eu scelerisque facilisis. Mauris bibendum, ex eu faucibus convallis, ante eros condimentum velit, eu dictum lectus felis eget justo. Proin faucibus blandit libero nec efficitur. Praesent eget condimentum ex. Pellentesque ligula magna, tempor vel vulputate eu, condimentum in augue. Nunc sagittis turpis diam, quis lacinia felis tristique in. Nam id risus a dolor dapibus rhoncus eget eu enim.</p>
            <p className="w-1/2 mb-4">Nullam ut ipsum mollis, facilisis ante at, convallis massa. Sed ornare urna ac ligula porttitor, ut tempus purus sollicitudin. Sed in vestibulum lorem. Maecenas a elit ante. Nulla vitae tempor odio. Nulla felis eros, volutpat at tortor pharetra, tincidunt hendrerit ligula. Praesent fermentum lectus ut turpis venenatis placerat. Duis velit odio, suscipit et libero iaculis, elementum efficitur mauris. Morbi ultricies vestibulum arcu quis bibendum. Praesent at dictum tortor. In consectetur sollicitudin diam, nec imperdiet odio fringilla in. Donec nec arcu a enim laoreet commodo. Phasellus in libero consectetur, feugiat nunc et, placerat risus. Nullam maximus ultricies sem, sed vestibulum velit consectetur eu. Suspendisse interdum at eros id condimentum. Pellentesque condimentum risus sed nibh vestibulum, a dapibus ligula egestas.</p>
            <p className="w-1/2 mb-4">Aliquam consectetur, erat eget blandit hendrerit, tellus arcu egestas ligula, sed commodo augue eros at augue. Nunc et purus accumsan, sagittis est sit amet, viverra lorem. Vivamus aliquam, massa non tristique malesuada, mi dui consectetur nisl, vel feugiat neque massa et nisl. Aliquam sed elit eu est tincidunt elementum. Suspendisse ante nibh, aliquam at egestas eu, fringilla vel libero. Proin tellus ex, mattis sit amet tincidunt sed, consequat ac erat. Suspendisse hendrerit dolor libero, sed mattis massa dapibus nec. Maecenas eros orci, ullamcorper nec porta eu, tincidunt sed diam. Cras id eros tempor, imperdiet turpis et, maximus magna. Suspendisse potenti. Aenean cursus ex ligula, a dapibus metus dictum at. In vitae dolor purus.</p>
        </div>
    )
}