import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Menu from "../components/Menu"
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Aula nextjs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body
				className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen antialiased`}
			>
				<UserProvider>
					<header className="flex w-full justify-items-start gap-4 p-4 bg-slate-900">
						<Link href="/">
							<img src="/home.svg" width={60} height={60} />
						</Link>
						<Menu />
					</header>

					<main className="flex-grow">
						{children}
					</main>

					<footer className="w-full p-6 text-center bg-slate-900">
						<p className="text-xl font-sans font-thin italic">&copy; todos os direitos reservados</p>
					</footer>
				</UserProvider>
			</body>
		</html>
	);
}
